# [ ==== ESP Home Info ==== ] #
esphome:
  name: esphome-web-[MAC_ADDR]
  friendly_name: ESPHome [FRIENDLY_NAME]
  min_version: 2025.9.0
  name_add_mac_suffix: false

# [ ==== PCB Board Info ==== ] #
esp32:
  variant: esp32dev
  framework:
    type: esp-idf

# [ ==== Logging, API, and Updates ==== ] #
logger:
api:
ota:
  - platform: esphome

# [ ==== WiFi Info ==== ] #
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

# [ ==== Web Server Info ==== ] #
web_server:
  port: 80
  version: 3

# [ ==== Time Configuration ==== ] #
time:
  - platform: homeassistant
    id: ha_time
    timezone: "America/Chicago"
#    on_time:
#      - seconds: 0
#        minutes: 0
#        hours: 0
#        then:

# [ ============================== External Packages ============================== ] #

# packages:
# remote_package_files:
#   url: https://github.com/SpicyLimes/[REPO]
#   files: YAML-Configs/[DEVICE]/[CONFIG_FILE].yaml
#   ref: main
#   refresh: 0s

# [ ============================================================================ ] #
