# [ ==== ESP Home Info ==== ] #
esphome:
  name: esphome-web-add694
  friendly_name: ESPHome LED Thermometer
  min_version: 2025.9.0
  name_add_mac_suffix: false

# [ ==== PCB Board Info ==== ] #
esp32:
  variant: esp32
  framework:
    type: esp-idf

# [ ==== Logging, API, and Updates ==== ] #
logger:
api:
ota:
  - platform: esphome

# [ ==== WiFi Info ==== ] #
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret house_wifi_ssid
      password: !secret house_wifi_password
  reboot_timeout: 0s
  fast_connect: true

# [ ==== Web Server Info ==== ] #
web_server:
  port: 80
  version: 3

# [ ==== Time Configuration ==== ] #
time:
  - platform: homeassistant
    id: ha_time
    timezone: "America/Chicago"
#    on_time:
#      - seconds: 0
#        minutes: 0
#        hours: 0
#        then:

# [ ============================== External Packages ============================== ] #

packages:
 remote_package_files:
   url: https://github.com/SpicyLimes/ESP32-Generic-Files
   files: YAML-Configs/ESP32-WROOM-32E/ESP32-32E_add694_v1-Package.yaml
   ref: main
   refresh: 0s

# [ ============================================================================ ] #
