# ESPHome ESPHome LED Thermometer
# esphome-web-add694
# File Description: External Package

# [ ==== Substitutions ==== ] #
substitutions:

# [ ==== Global Values ==== ] #
globals:

# [ ==== Buttons ==== ] #
button:
  - platform: factory_reset
    name: "Factory Reset - ESPHome LED Thermometer"
    icon: mdi:restart

# [ ==== Lights ==== ] #
light:
  - platform: status_led
    name: "Status LED - ESPHome LED Thermometer"
    icon: mdi:led-on
    pin: 
      number: GPIO2
      ignore_strapping_warning: true

# [ ==== Sensors ==== ] #
sensor:

# [ ==== Text Sensors ==== ] #
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address - ESPHome LED Thermometer"
      icon: mdi:ip-network
  - platform: version
    name: "ESPHome Version - ESPHome LED Thermometer"
    icon: mdi:car-esp

# [ ==== Binary Sensors Configuration ==== ] #
binary_sensor:
  # ESP32 Boot Button
  - platform: gpio
    pin:
      number: GPIO0  
      ignore_strapping_warning: true
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Boot Button - ESPHome LED Thermometer"
    icon: mdi:gesture-tap-button
