# [ ==== ESP Home Info ==== ] #
esphome:
  name: esphome-web-[MAC_ADDR]
  friendly_name: ESPHome [FRIENDLY_NAME]
  min_version: 2025.9.0
  name_add_mac_suffix: false

# [ ==== PCB Board Info ==== ] #
esp32:
  board: esp32dev
  framework:
    type: esp-idf

# [ ==== Logging, API, and Updates ==== ] #
logger:
api:
ota:
  - platform: esphome

# [ ==== WiFi Info ==== ] #
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

# [ ==== Web Server Info ==== ] #
web_server:
  port: 80
  version: 3

# [ ==== Time Configuration ==== ] #
time:
  - platform: homeassistant
    id: ha_time
    timezone: "America/Chicago"
#    on_time:
#      - seconds: 0
#        minutes: 0
#        hours: 0
#        then:

# [ ============================== External Packages ============================== ] #

packages:
 remote_package_files:
   url: https://github.com/SpicyLimes/ESP32-S3-Files
   files: YAML-Configs/ESP32-WROOM-32E/ESP32-[BOARD]_[MAC_ADDR]-[BASE_PACKAGE]_v[VERSION].yaml
   ref: main
   refresh: 0s

# [ ============================================================================ ] #


# [ ==== Substitutions ==== ] #
substitutions:

# [ ==== Global Values ==== ] #
globals:

# [ ==== Buttons ==== ] #
button:
  - platform: factory_reset
    name: "Factory Reset - [FRIENDLY_NAME]"
    icon: mdi:restart

# [ ==== Lights ==== ] #
light:
  - platform: status_led
    name: "Status LED - [FRIENDLY_NAME]"
    icon: mdi:led-on
    pin: 
      number: GPIO2
      ignore_strapping_warning: true

# [ ==== Sensors ==== ] #
sensor:

# [ ==== Text Sensors ==== ] #
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address - [FRIENDLY_NAME]"
      icon: mdi:ip-network
  - platform: version
    name: "ESPHome Version - [FRIENDLY_NAME]"
    icon: mdi:car-esp

# [ ==== Binary Sensors Configuration ==== ] #
binary_sensor:
  # ESP32 Boot Button
  - platform: gpio
    pin:
      number: GPIO0  
      ignore_strapping_warning: true
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Boot Button - [FRIENDLY_NAME]"
    icon: mdi:gesture-tap-button
